import React from 'react';
import Dictators from '../dictators'
import {Helmet} from 'react-helmet';
import { Link } from "react-router-dom";
import createScrollSnap from 'scroll-snap'

class Landing extends React.Component {
    container = React.createRef()
    bindScrollSnap() {
        const element = this.container.current
        createScrollSnap(element, {
        snapDestinationY: '90%',
        }, () => console.log('snapped'))
    }

    state = {...Dictators};
    components = [];

    componentDidMount() {
        Object.keys(this.state).map((key, index) => {
            this.setState(prevState => {
                let newState = {...prevState[key]};
                const Component = (
                    <Link to={`/${key}`} className="link-link" key={index}>
                <div className="timeline-wrapper" id={key}>
                    <h3>De voordelen van <b>{key}</b> - van {this.state[key]["date"].split(" - ")[0]} tot {this.state[key]["date"].split(" - ")[1]}</h3>
                    <ul className='timeline' index={index}>
                        {this.state[key]["importantDates"].map((importantDateObject, index) => <Link key={index} className="link-link" to={`/${key}/${importantDateObject["date"]}`}><li key={index} style={{color: 'white'}} data-year={importantDateObject["date"]}></li></Link>)}
                    </ul>
                </div></Link>
                );
                newState["Component"] = Component;
                this.components.push(() => { return Component});
                prevState[key] = newState;
                return prevState;
            })
        })
    }

    render() {
        return(
            <div className="scroller" id="container" ref={this.container}>
                <Helmet>
                    <style>{'body { background-color: #28282e !important; color: #fff !important;}'}</style>
                </Helmet>
                <section className='page'>
                    {this.components.map((Component, index) => <Component key={index}/>)}
                </section>
                <section>
                    <div className='all-content'>
                        <h1>Hoe gebruik ik dit?</h1><br/><br/>
                        <p>Deze web-applicatie is te gebruiken op 3 verschillende manieren:</p><br/><br/>
                        <ol>
                            <li>Door te klikken op de tijdlijn, waarna u op de pagina van een dictator komt, en u de tijdlijn rechts kunt gebruiken, of naar beneden kunt scrollen</li><br/>
                            <li>Door te klikken op een van de jaartallen op de tijdlijnen, wordt u doorgestuurd naar dat jaartal, waarna u kunt verderkijken naar andere jaartallen, of terug kunt gaan</li><br/>
                            <li>U kunt ook op deze pagina naar beneden scrollen, waardoor u deze informatie krijgt te lezen</li><br/>
                        </ol>
                    </div>
                </section>
                <section>
                    <div className='all-content'>
                        <h1>Wat is dit?</h1>
                        <p>Voor een project in het Corlaer College geschiedenis, moesten wij een onderwerp vinden die verzwegen is, eentje die vrijwel niet terug te vinden is in de geschiedenisboeken omdat mensen actief eromheen praten. Ik dacht hierbij vrijwel direct aan de VOC/WIC met de slavenhandel, alleen had ik die al genomen voor een vorig PO. Dus toen dacht ik aan de voordelen van vroegere dictators. Iedereen hoort van de gruweldaden die dictators hebben verricht, maar de dictators zitten op dat moment in zo’n enorme machtspositie dat ze zonder toestemming van andere mensen wijzigingen door kunnen voeren, dit betekent dat ze alles in een land kunnen veranderen. Als ze het volk te boos maken, is de kans groot dat de dictator op een wellicht gewelddadige manier afgezet wordt, dus moeten ze in ieder geval iets doen om het volk blij te houden. Omdat we vrij weinig tijd hadden voor het onderzoek, moesten we kijken naar maar 3 verschillende dictators en de algemene voordelen die ze theoretisch <em>kunnen</em> hebben. Daarbij moeten er ook, vooral in de tijd van Napoleon, grote veranderingen geweest zijn om de bevolking van zo een gigantisch rijk belastinggeld laten betalen. Een heel bekend voorbeeld hiervan die vrijwel iedereen kent is dan ook van Napoleon, wie het idee van achternamen bedacht had en geadopteerd heeft om mensen makkelijker te belasten.</p><br/>
                        <p>Voor dit onderzoek hadden we meerdere deelvragen:</p><br/>
                        <ol style={{marginLeft: "40px"}}>
                            <li>Welke voordelen kunnen dictatorschap hebben voor de bevolking van een gebied?</li>
                            <li>Welke positieve (technologische en andere) vooruitgangen zijn geboekt door de dictators?</li>
                            <li>Hoeveel positieve vooruitgangen zijn dit vergeleken met democratische gebieden?</li>
                            <li>In welke situaties zijn dictaturen handiger dan democratisch-bestuurde landen?
                                <ol type="a" style={{marginLeft: "40px"}}><li>Zijn de historische dictaturen in deze situaties ook opgestart?</li></ol>
                            </li>
                        </ol>
                    </div>
                </section>
                <section>
                    <div className='all-content'>
                        <h1>De theoretische voordelen</h1>
                        <p>Hoewel in lange termijn een dictatuur veel schade kan aanrichten, kan het ook voordelen hebben. Als grootste voordeel zijn politieke keuzes snel gemaakt; terwijl er in een democratisch gebied lang gedebatteerd moet worden, is er maar één persoons keuze nodig om een amendement door te laten gaan in een dictatuur. Hoewel dit in de praktijk veel corruptie door laat komen, in theorie zorgt dit ervoor dat in noodsituaties, keuzes snel gemaakt kunnen worden.</p><br/>
                        <p>Een goed voorbeeld van het bovenstaande is de corona-pandemie: hoewel de data betwijfelbaar is gezien ze veel invloed in de WHO hebben, had China enorm lage corona-cijfers. Omdat de “Volksrepubliek” van China Xi Jinping heeft toegewezen als dictator, moesten er snel keuzes gemaakt worden. In sommige gevallen werden mensen letterlijk dichtgelast in hun huizen en in aanloop van de olympische spelen werden mensen in miljoenensteden in enorm hoog tempo geforceerd te testen. Vrij veel mensen hebben tragischerwijs zelfmoord gepleegd door uit hun raam te springen om te proberen vrij te komen. Hoewel dit voor de bevolking erg heftige maatregelen zijn en hun leven vrij letterlijk een gevangenis heeft gemaakt, en dit slechts de maatregelen zijn waarvan wij westerners hebben gehoord, was het wel effectief.</p><img src="images/image3.png" className='source-graph'/><br/>
                        <p>Dit houdt alleen niet in dat dictaturen per definitie sneller zijn in het oplossen van dit soort problemen, volgens Petersen, German (2020) is de grafiek een u-vormig figuur.<br/><img src="images/image2.png" className='source-graph'/><br/>In hetzelfde onderzoek is ook een verband gevonden tussen BBP, hoeveelheid tests en gemeente effectiviteit, waarin dictaturen een hoger effectiviteit hebben per BBP dan democratisch gestuurde landen. Hiervoor wordt gecorrigeerd in het onderzoek gedaan door Alon, I., Farrell, M., &amp; Li, S. (2020), waaruit bleek dat Taiwan, Noord-Korea en Japan het beste effectiviteit van het verhelpen van een pandemie hebben; de conclusie daarvan was dat verantwoordelijkheid naar de bevolking hier de belangrijkste factor is in alle politieke systemen. Dit houdt in dat waar bij een democratie er geen 1 partij is die iets fout doet, maar meerdere ministers zijn die de keuze maken, is er in een dictatuur altijd maar 1 verantwoordelijke. Democratieën waar makkelijker te zien is wie verantwoordelijk is voor bepaalde onderwerpen, zoals in Nederland, scoren beter dan andere landen.</p><br/>
                        <p>Ook in economisch wanhopige tijden werkt een dictatuur sneller dan een democratisch land; na de Grote Depressie van 1929 viel de hoeveelheid democratische landen naar een dieptepunt van maar 21,31% democratische landen.<br/><img src="images/image4.png" className='source-graph'/><br/>Ook is te zien dat veel dictators in economisch wanhopige tijden aan de macht kwamen en de economie een stuk te verbeteren (zie hoofdstuk “De positieve vooruitgangen”).</p><br/>
                        <p>Volgens Y. Harari (2018) is de verwachting dat waar kunstmatige intelligentie verbetert, dictaturen zullen volgen. Hij ziet dat de afgelopen tijd alleen maar democratieën hebben gewonnen van dictaturen omdat ze sneller informatie kunnen verwerken: “In de late 20e eeuw presteerden democratieën meestal beter dan dictaturen, omdat ze veel beter waren in het verwerken van informatie”. Dit was volgens hem ook waarom de Sovjet-Unie zo ver achter de Verenigde Staten lag bij bepaalde punten. Zodra kunstmatige intelligentie meer op de voorgrond komt te liggen, zullen dictaturen net zo snel of zelfs sneller data verwerken, en omdat keuzes sneller gemaakt kunnen worden, worden dictaturen over het algemeen een stuk sneller.</p>
                    </div>
                </section>
                <section>
                    <div className='all-content'>
                        <h1>Dictatuur in vergelijking met democratische gebieden</h1>
                        <p>Om te kijken naar de voordelen van Hitler, Mussolini en Napoleon in hun tijd als dictator moeten we ook kijken naar wat de democratische gebieden op die tijd voor eventuelen voordelen hadden om ze zo te kunnen vergelijken met elkaar en te zien om qua voordelen dictaturen ook echt op sommige punten beter kunnen zijn dan democratische gebieden.</p>
                        <p>Voordat Hitler dictator werd was Duitsland een republiek genaamd de "Weimar republiek". Duitsland werd een republiek omdat de keizer Wilhelm II afgezet was en ze een nieuwe bestuursvorm nodig hadden. Doordat Duitsland de grote verliezer was en als vijand werd gezien door een hele hoop landen had de Weimar republiek een hele hoop grote problemen. Een voorbeeld daarvan is de enorme schulden die ze hadden aan onder andere Frankrijk en Amerika. Dit werd pas echt een probleem in 1929 toen de beurskrach plaatsvond. Hierdoor kwam Amerika in een enorme economische crisis en gingen ze de schulden die Duitsland aan hun had eisen. Hierdoor kwam Duitsland in een diepe economische put terecht. Hier komt Hitler in het verhaal. Hij zag hoe Duitsland kapot ging door de andere landen en beloofde een oplossing. Het Duitse volk leed en toen iemand zei dat hij alles ging oplossen geloofde ze hem. Als dictator maakte hij zijn beloftes waar en hielp hij Duitsland uit de economische crisis. Hij zorgde voor autarkie en dingen als de autobahn en in slechts 12 jaar had hij Duitsland van een vernederd en economisch zwak land naar een welvarend en machtig land dat land na land veroverde in de Tweede Wereldoorlog. Natuurlijk was de tweede wereldoorlog negatief en verschrikkelijk maar als je kijkt naar hoe erg die republiek faalde en Hitler in zo'n korte tijd het land zo machtig heeft kunnen maken is echt iets wat alleen door snelle beslissingen en goed denkwerk van 1 man, 1 dictator met alle macht die zoiets voor elkaar kreeg.</p><br/>
                        <p>Voordat Mussolini de macht nam en dictator werd van Italië was het een soort democratie. In Italië (van 1865 tot en met 1923) heerste er daar ook een soort democratie. Na de eerste wereldoorlog kwamen ze wel een beetje in de problemen met schulden, tekorten aan voedsel, slechte oogst en hevige inflatie. In deze tijd ontstond de Biennio Rosso, een 2 jarige periode waar het land veel interne sociale conflicten had. Mussolini zag dit en maakte er gebruik van door met het fascisme de bedoeling te hebben het land te regeren. Dit gebeurde ook in wat nu de "march on Rome" wordt genoemd. Het fascisme was een systeem waar werd gedacht dat je 1 partij zou moeten hebben zodat die alle beslissingen kunnen maken. Dit houdt in dat ze sneller kunnen reageren op militaire dreigingen en economische problemen. Als je kijkt naar militaire dreigingen in die tijd en hoe de democratische landen dat oppakte kan je zien wat voor problemen een democratie met zich meebrengt op dat gebied.</p><br/>
                        <p>Neem Hitler als voorbeeld. Het was iets later maar hij begon met het veroveren van landen en zelfs voordat de Tweede Wereldoorlog begon omdat ze eindelijk genoeg hadden lieten ze Hitler elk land makkelijk invallen en overnemen waardoor hij zo zijn macht kon vergroten. Zelfs in de oorlog was een democratisch land als Amerika erg aan het twijfelen of ze meer moesten doen, het land was namelijk erg verdeeld over oorlog en omdat het democratisch is duurde het nemen van beslissingen langer.</p><br/>
                        <p>Toen Mussolini aan de macht kwam en het fascisme werd ingesteld kon Mussolini snel en gemakkelijk grote beslissingen nemen wat misschien een nadeel was voor het kiezen van een kant in de Tweede Wereldoorlog, maar op economisch gebied erg goed was. Al de economische schade die was gedaan aan Italië als gevolg van de Tweede Wereldoorlog wist Mussolini op te lossen in enorm snel tempo. Hij zorgde ervoor dat het land minder afhankelijk was van handel met andere landen en door de economisch sector volledig kunnen te controleren ging de welvaart snel omhoog. Hij was door zijn succes ook erg populair in Amerika, tot de Tweede Wereldoorlog. Winston Churchill (minister-president van het Verenigd Koninkrijk in de Tweede Wereldoorlog) zei zelfs: "If I had been Italian, I am sure I would have been with you from the beginning". Mussolini werd gezien als een machtig en slimme man en zijn economisch fascisme wordt zelfs vergeleken met Obamacare, een systeem opricht door Obama in zijn presidentschap om ervoor te zorgen dat er iets van een ziektevergoeding zou komen voor de Amerikanen aangezien die geen gezondheidsverzekering hebben. Hij had hierdoor een monopoly op dit gebied en dus konden verzekeringsmaatschappij - al zouden ze willen - niet zelf een verzekering verkopen en daarvoor enorme prijzen vragen.</p><br/>
                        <p>Het economisch fascisme had dus een hele hoop voordelen en Mussolini had veel voordelen dan de democratie die er daarvoor heerste. Het grote nadeel ligt dus bij het fascisme zelf en de kant aan wie Mussolini stond, maar als je kijkt naar de goede dingen die hij heeft gedaan voor Italië zou je kunnen zeggen dat hij nog best een goede leider was op dat front. Ook was het verbieden van invoer en uitvoer in Italië misschien niet het beste idee, hoewel het Italië zelfstandiger maakte konden ze niet groeien door handel uit andere landen die zich weer in andere dingen specialiseren.</p><br/>
                        <p>Napoleon Bonaparte was een dictator van 1804 tot 1814 en heeft voor veel lijden gezorgd. Dit is over het algemeen erg bekend. Wat minder wordt verteld zijn alle goede dingen die hij in zijn leven heeft gedaan. Zoals eerder vermeld was hij een briljante generaal die het respect van zijn soldaten had verdiend, zijn oorlogsstrategieën waren fantastisch, hij maakte een gecentraliseerd wetboek, bracht het metriek stelsel in het systeem, zorgde voor gelijkheid tussen mannen, hij maakte Frankrijk een Europese supermacht en hij was degene die achternamen had bedacht. Een democratisch gebied en beter gezegd 1 persoon om Napoleon mee te vergelijken is George Washington: De eerste president van de Verenigde Staten. Als we kijken naar hun kunnen we zien dat ze eigenlijk best erg op elkaar leken. Er was alleen 1 gebied waar ze beide aan de andere kanten van het spectrum zaten.</p><br/>
                        <p>Frankrijk en de Verenigde Staten zaten rond dezelfde tijd met het probleem van revolutionaire ideeën en uiteindelijk revolutie. Napoleon was in de tijd van de Franse revolutie generaal en profiteerde erg van de chaos die door niet alleen die revolutie maar ook door de hyperinflatie, dreigende burgeroorlog en het terreur ontstond. Hij vocht mee aan de revolutie en hielp met het stoppen van de mensen die tegen de revolutie waren. Hier kwamen de mensen te zien wat voor goede generaal hij was. Hij won het vertrouwen van zijn soldaten. Hij besloot ook om er wat te doen aan al die chaos en beloofde het de bevolking een oplossing voor de problemen in het land, won het vertrouwen van het volk en werd zo uiteindelijk een dictator. Zijn oorlogsstrategieën bleken fantastisch te zijn en wist te winnen tegen de republiek van de 7 Verenigde Nederlanden en zorgde ervoor dat Oostenrijk "De Vrede van Campo Formio" moest tekenen waardoor Frankrijk meer land kreeg. Uiteindelijk in 1815 in de bekende Slag om Waterloo waarin hij met 73.000 soldaten tegen 67.000 geallieerde en 60.000 vocht en het dodental redelijk gelijk hield wat enorm knap is aangezien hij enorm in de minderheid was. Dit laat echt zien wat voor geniale leider hij bleek te zien op het gebied van zijn oorlogsstrategieën.</p><br/>
                        <p>George Washington werd generaal van het Amerikaanse leger in 1775 dat als doel had mee te doen met de revolutie tegen de Britten die Amerika als kolonie hadden. Hij leidde het leger in verschillende slagen zoals de slag om Concord. Daarna zorgde hij voor het trainen van de Amerikaanse soldaten tegen de britten. Hij liet zijn soldaten zijn moed zien en inspireerde de soldaten. De soldaten aan je kant hebben is iets wat natuurlijk erg handig is en door zijn daden werd hij uiteindelijk gezien als held van de revolutie die uiteindelijk succesvol was door de hulp die de Franse troepen gaven aan Amerika om de Britten te verslaan, dit koste alleen erg veel geld en kwam Frankrijk in de problemen die Napoleon later zou helpen met oplossen. In 1783 ging George uit het leger en terug in de plantages. Na de komst van de grondwet in 1789 moest er een president komen. Door de status held die George had gekregen door de revolutie werd al snel besloten dat hij president zou moeten worden. Dit wou George eerst niet aangezien hij liever zijn leven en baan op de plantages had. Maar door de enorme hoeveelheid stemmers was het niet echt iets wat hij zomaar kon weigeren. En dus werd George in 1789 de eerste president van de Verenigde Staten, hij bleef dat tot 1797 en stierf in 1799. Interessant in dat na zijn dood Napoleon een rouwperiode van 10 dagen aankondigde in respect voor George Washington.</p><br/>
                        <p>Er zijn dus veel dingen die Napoleon en George verbinden. Van de Fransen die George en heel Amerika hielpen tot na George zijn dood waarin Napoleon voor hem rouwde. Maar wat maakte het dat George als de grote held wordt gezien en Napoleon als een grote gemene dictator terwijl ze op veel punten gelijk stonden en goede dingen deden voor het land. Ik heb hiervoor vooral de goede dingen uitgelegd maar nu wordt het tijd te kijken naar de wat minder goede dingen.</p><br/>
                        <p>Napoleon was een van de meest bekende dictators van 1804 tot 1814. Hij vocht met een heleboel landen zoals het Verenigd Koninkrijk, Duitsland (of delen ervan), Oostenrijk, Pruisen, de Russen en meer. Dit leed in best wat vijanden en dus vond een groot deel van Europa hem niet zo heel erg leuk. Maar het grootste ding dat er voor zorgde dat hij werd gezien als een slechte dictator was het vernietigen van opkomende idealen en het verbieden van vrije spraak door mensen hun stem niet in kranten en andere vormen van media te laten staan. Hij was de keizer en alleen zijn mening telde. Dit is iets waar meerdere dictators de fout in gaan. Ook zijn er velen tot dood veroordeeld door napoleon. Niet zo heel prettig dus en eigenlijk de grote reden waarom we hem nu meer als een slechterik zien dan bijvoorbeeld George Washington.</p><br/>
                        <p>Wel is het interessant om te kijken naar George Washington zijn slavenbedrijf. Hij was een slavendrijver en hoewel dat in die tijd normaal was is dat nu zeker niet het geval. Als zowel George als Napoleon vandaag de dag zouden leven betwijfel ik of we ze nog steeds zoveel anders van elkaar zouden vinden en we zowel George de held van de revolutie en president en Napoleon dictator en keizer van Frankrijk als verkeerde mensen beschouwen.</p>
                    </div>
                </section>
                <section>
                    <div className='all-content'>
                        <h1>In welke situaties zijn dictaturen handiger dan democratisch-bestuurde landen?</h1>
                        <p>Door te kijken naar zowel de voor- en nadelen van voorgaande dictaturen en ook te kijken naar hoe dat was in vergelijking met de democratische gebieden van die tijd kan je interessante conclusie proberen te trekken.</p><br/>
                        <q>"Power tends to corrupt and absolute power corrupts absolutely." - Lord Acton</q><br/>
                        <p>Dit is een quote die best relevant is voor het beantwoorden van de deelvraag die hierboven wordt gesteld. Vooral op het gebied van dictators en gebieden die bestuurd worden door 1 groep of persoon is de quote erg belangrijk. Door de enige groep of persoon te zijn die de macht heeft over het land hebben ze de absolute macht en zoals gesteld wordt in de quote wordt die macht erg makkelijk corrupt. Dit is over het algemeen het grootste probleem als je dictaturen vergelijkt met democratische bestuurde landen.</p><br/>
                        <p>Als je kijkt naar hoe Mussolini en Hitler een vallend land met een enorm slecht democratisch systeem dat blijkt te falen door de oorlog is het een logische keuze dat je een dictatuur ingesteld. Als je in die tijden een nieuwe democratie had geprobeerd was het niet beter gegaan. Het klinkt nu een beetje alsof dictaturen de enige oplossing was wat niet zo is, maar het nemen van snelle beslissingen en economische groei was iets wat in die tijd hard nodig was. Op een bepaalde manier kan je zeggen dat hoe slecht Hitler en Mussolini en hun ideale ook waren was hun manier van aanpak op gebied van economie op dat moment hetgeen wat het land redde. Beide landen zaten diep in de put en door het snelle beslissingen maken kon zowel Italië en Duitsland enorm hard groeien.</p><br/>
                        <p>Napoleon was ook iemand die voor veel welvaart zorgde in Frankrijk en veel belangrijke dingen de wereld in bracht. Ook hij nam een arm Frankrijk en redde het op een bepaalde manier. Hij zorgde voor achternamen, het metriek stelsel in Frankrijk, had brilliante oorlogsstrategieën, zorgde voor gelijkheid tussen mannen en zorgde voor de Napoleontische Code. Een nadeel is dat hij te dicht bij de zon vloog met het oorlogvoerende en uiteindelijk veels te veel landen tegen zich had. Ook waren zijn politieke idealen en manier van censuur verschrikkelijk.</p><br/>
                        <p>Door dit te analyseren zou je kunnen zeggen dat hoewel de snelle beslissingen waar democratische gebieden langer over doen voor veel voordelen kan zorgen. Vooral economisch gezien zie je hoe goed Hitler, Mussolini en Napoleon allemaal voor enorm veel economische welvaart gaf aan landen die het erg nodig hadden. Het nadeel ligt vooral bij de idealen die de dictators hebben. Op politiek, sociaal gebied en oorlogsvoering kunnen de dictators vaak grootheidswaanzin krijgen en de verkeerde beslissingen nemen die hoewel vaak eerst goed gaan uiteindelijk falen door het maken van te veel vijanden die samenkomen om de dictator te verslaan. Het grote nadeel is dat je in je eentje bent en dat eenmaal uiteindelijk fout gaan. Het is dus een "high risk high reward" strategie om een dictatuur te hebben.</p><br/>
                    </div>
                </section>
                <section>
                    <div className='all-content'>
                        <h1>Conclusie</h1>
                        <p>In het eerste hoofdstuk werd verteld over de voordelen van dictators waar we achter kwamen dat hoewel het best wel wordt verzwegen en weggestopt door alle slechte dingen dictaturen ook voor veel goede dingen zorgen door het nemen van snelle beslissingen die voor bijvoorbeeld covid erg positief waren zoals te zien in de covid gevallen van china in vergelijking met Nederland.</p><br/>
                        <p>Het mooie van dictaturen zijn de vooruitgangen die werden uitgelicht in hoofdstuk 2. Hier was te zien dat er eigenlijk best veel goede vooruitgangen waren die vandaag de dag nog relevant zijn, neem achternamen en het metriek stelsel bijvoorbeeld. Ook wordt uitgelicht hoe bijvoorbeeld Duitsland uit een diepe economische put kwam door de snelle belangrijke beslissingen die Hitler nam om die welvaart te laten groeien.</p><br/>
                        <p>Toen werd het tijd de dictators Hitler, Mussolini en Napoleon te vergelijken met democratische gebieden. Hier werd verteld hoe iedere dictator aan zijn macht kwam en in wat voor staat het land was voordat zijn aan de macht kwamen. Daarna werd het vergeleken met democratische gebieden rond die tijd en wat voor verschillen ertussen zaten.</p><br/>
                        <p>Uiteindelijk in hoofdstuk vier was het tijd om te kijken wat de echte voordelen waren van de 3 dictators in vergelijking met de democratische gebieden. Hier kwam er een patroon naar voren. Alle 3 de dictators begonnen goed en waren erg slimme en talentvolle mannen die het volk voor zich won en gebruik maakte van de problemen die hun land had en het beloofde op te lossen. Ze kwamen aan de macht en onder hun macht zag je de economische welvaart erg omhoog ging in een korte tijd door de snelle beslissingen die konden worden gemaakt. Maar het probleem ligt in zoals in de quote van Lord Acton: "Power tends to corrupt and absolute power corrupts absolutely."</p><br/>
                        <p>Met 1 iemand die alle macht krijgt is te zien dat dat eenmaal fout gaat. Absolute macht is te veel voor 1 persoone en hoewel ze eerst misschien we de goede intentie hadden is het creeën van slechte idealen een groot probleem, de macht wordt corrupt. Zo laat Napoleon andere mensen niet hun mening geven in de kranten en zocht oorlog met veel landen en zag je Hitler en Mussolini met hun verschillende idealen zoals ariërs en het fascisme.</p><br/>
                        <p>Dan komen we aan bij de uiteindelijke vraag: Waarom is ons onderwerp verzwegen geschiedenis? Dit heeft verschillende redenen.</p><br/>
                        <p>Belangrijk is om te kijken naar uitkomst van de conflicten en aan welke kant van de geschiedenis de dictators allemaal belandde. Stuk voor stuk belandde ze allemaal als verliezers van grote conflicten en dus ook de slechte kant van de geschiedenis. Zoals Winston Churchill zei: "History is written by the victor." En aangezien de dictators allemaal verliezers waren zou je je kunnen voorstellen dat de winnaars en dus vijanden van de dictators niet zo veel goede dingen wouden zeggen over hun vijand.</p><br/>
                        <p>Dan heb je het feit dat hoewel er veel goede dingen zijn gekomen uit het dictatorschap van Hitler, Mussolini en Napoleon die worden overschaduwd door de slechte dingen die ze deden. Hitler met genocide, Mussolini met aan de kant staan van Hitler en een erg agressieve dictator zijn en Napoleon met zijn manier van censuur.</p><br/>
                        <p>Leren van het verleden en voor een betere toekomst zorgen is tenslotte waar geschiedenis over gaat en dus is het belangrijk zo min mogelijk dingen verzwegen te houden. Te beginnen met de volgende generatie het hele plaatje te geven over de 3 van de meest bekende en ook beruchte dictators die ooit bestonden.</p><br/>
                    </div>
                </section>
            </div>
        )
    }
}

export default Landing;